#!/usr/bin/env bash
command -v realpath >/dev/null
if [ ! $? ]; then
  # resolve for mac
  function realpath() {
    python3 -c "import os; print(os.path.abspath('$1'))"
  }
fi

CUR_DIR=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

source "$CUR_DIR/../.env"

export PYTHONPATH
export AIRFLOW_HOME
export DAGS_FOLDER
export AIRFLOW__CORE__LOAD_EXAMPLES
export AIRFLOW__CORE__LOGGING_CONFIG_CLASS
export AIRFLOW__LOGGING__LOGGING_CONFIG_CLASS
export AIRFLOW__CORE__DAGS_FOLDER

if [ "$#" -eq 0 ]; then
  source "$CUR_DIR/configure"
  airflow standalone
else
  airflow "$@"
fi
